local nav = require("ascii-ui-actions.logic.nav")
local eq = require("tests.assertions").eq

local function s0()
	return nav.initial({ repo = "o/r" })
end

describe("logic.nav", function()
	it("opens on workflows when a repo is configured", function()
		local s = s0()
		eq("workflows", s.view.kind)
		eq("o/r", s.view.repo)
		eq("loading", s.status)
		eq(1, s.seq)
	end)

	it("opens on the picker when no repo is configured", function()
		local s = nav.initial({})
		eq("detect", s.view.kind)
	end)

	it("open_workflows bumps seq and clears data", function()
		local s = nav.reduce(s0(), { type = "FETCH_OK", seq = 1, data = { workflows = {} }, at = "12:00" })
		s = nav.reduce(s, { type = "NAV", kind = "open_workflows", repo = "a/b" })
		eq("a/b", s.view.repo)
		eq("loading", s.status)
		assert(s.data == nil, "data cleared")
		eq(2, s.seq)
	end)

	it("stale FETCH_OK (seq mismatch) is dropped", function()
		local s = nav.reduce(s0(), { type = "NAV", kind = "open_runs", workflow_id = "ci.yml" })
		eq("runs", s.view.kind)
		local after = nav.reduce(s, { type = "FETCH_OK", seq = 1, data = { workflows = { "stale" } } })
		assert(after == s, "state untouched by stale response")
	end)

	it("fresh FETCH_OK applies with matching seq", function()
		local s = nav.reduce(s0(), { type = "NAV", kind = "open_runs", workflow_id = "ci.yml" })
		s = nav.reduce(s, { type = "FETCH_OK", seq = s.seq, data = { runs = { { id = 1 } } }, at = "now" })
		eq("ready", s.status)
		eq(1, s.data.runs[1].id)
		eq("now", s.fetched_at)
		assert(s.stale == false)
	end)

	it("back walks the view stack", function()
		local s = nav.reduce(s0(), { type = "NAV", kind = "open_run_detail", run = { id = 5 } })
		eq("run_detail", s.view.kind)
		s = nav.reduce(s, { type = "NAV", kind = "back" })
		eq("runs", s.view.kind)
		eq("o/r", s.view.repo)
		s = nav.reduce(s, { type = "NAV", kind = "back" })
		eq("workflows", s.view.kind)
		s = nav.reduce(s, { type = "NAV", kind = "back" })
		eq("picker", s.view.kind)
	end)

	it("run_detail back keeps workflow context", function()
		local s = nav.reduce(s0(), { type = "NAV", kind = "open_runs", workflow_id = "ci.yml", workflow_name = "CI" })
		s = nav.reduce(s, { type = "NAV", kind = "open_run_detail", run = { id = 9 } })
		s = nav.reduce(s, { type = "NAV", kind = "back" })
		eq("runs", s.view.kind)
		eq("ci.yml", s.view.workflow_id)
	end)

	it("back at the root is a no-op", function()
		local s = nav.initial({})
		s = nav.reduce(s, { type = "NAV", kind = "open_workflows", repo = "o/r" })
		s = nav.reduce(s, { type = "NAV", kind = "back" })
		eq("picker", s.view.kind)
		s = nav.reduce(s, { type = "NAV", kind = "back" })
		eq("picker", s.view.kind)
	end)

	it("refresh bumps seq but keeps the view", function()
		local s = s0()
		s = nav.reduce(s, { type = "FETCH_OK", seq = 1, data = { workflows = { 1 } } })
		s = nav.reduce(s, { type = "NAV", kind = "refresh" })
		eq(2, s.seq)
		eq("workflows", s.view.kind)
		eq("loading", s.status)
	end)

	it("refresh errors keep the cached payload marked stale", function()
		local s = s0()
		s = nav.reduce(s, { type = "FETCH_OK", seq = 1, data = { workflows = { 1 } } })
		s = nav.reduce(s, { type = "NAV", kind = "refresh" })
		s = nav.reduce(s, { type = "FETCH_ERR", seq = s.seq, error = { kind = "api", message = "boom" } })
		eq("ready", s.status)
		assert(s.stale, "stale marker set")
		eq(1, #s.data.workflows)
		eq("boom", s.error.message)
	end)

	it("first-load errors set the error status", function()
		local s = s0()
		s = nav.reduce(s, { type = "FETCH_ERR", seq = 1, error = { kind = "gh_missing", message = "no gh" } })
		eq("error", s.status)
		assert(s.data == nil)
		eq("gh_missing", s.error.kind)
	end)

	it("load_more bumps page and merges the next payload", function()
		local s = nav.reduce(s0(), { type = "NAV", kind = "open_runs", workflow_id = "ci.yml" })
		s = nav.reduce(s, { type = "FETCH_OK", seq = s.seq, data = { runs = { { id = 1 } }, total = 3 } })
		s = nav.reduce(s, { type = "NAV", kind = "load_more" })
		eq(2, s.view.page)
		s = nav.reduce(s, { type = "FETCH_OK", seq = s.seq, data = { runs = { { id = 2 } }, total = 3 } })
		eq(2, #s.data.runs)
		eq(1, s.data.runs[1].id)
		eq(2, s.data.runs[2].id)
	end)

	it("pending actions: request → confirm → result; double request blocked", function()
		local s = s0()
		s = nav.reduce(s, { type = "ACTION_REQUEST", action = "rerun", target = { run_id = 1 } })
		eq("confirm", s.pending_action.state)
		local dup = nav.reduce(s, { type = "ACTION_REQUEST", action = "cancel", target = { run_id = 2 } })
		eq("rerun", dup.pending_action.kind, "second request ignored while one is pending")
		s = nav.reduce(s, { type = "ACTION_CONFIRM" })
		eq("running", s.pending_action.state)
		s = nav.reduce(s, { type = "ACTION_RESULT", message = "rerun started" })
		assert(s.pending_action == nil, "pending cleared")
		eq("rerun started", s.action_message)
	end)

	it("dispatch action opens in form state; ref update; abort clears", function()
		local s = s0()
		s = nav.reduce(
			s,
			{ type = "ACTION_REQUEST", action = "dispatch", target = { workflow_id = "ci.yml" }, ref = "main" }
		)
		eq("form", s.pending_action.state)
		s = nav.reduce(s, { type = "ACTION_REF", ref = "dev" })
		eq("dev", s.pending_action.ref)
		s = nav.reduce(s, { type = "ACTION_ABORT" })
		assert(s.pending_action == nil)
	end)

	it("navigation clears pending_action", function()
		local s = s0()
		s = nav.reduce(s, { type = "ACTION_REQUEST", action = "rerun", target = {} })
		s = nav.reduce(s, { type = "NAV", kind = "back" })
		assert(s.pending_action == nil, "pending dropped on navigation")
	end)

	it("SEARCH_DONE only lands on the picker view", function()
		local s = nav.initial({})
		s = nav.reduce(s, { type = "NAV", kind = "open_picker" })
		s = nav.reduce(s, { type = "SEARCH_DONE", results = { { fullName = "a/b" } }, query = "a" })
		eq(1, #s.data.results)
		local t = nav.reduce(s, { type = "NAV", kind = "open_workflows", repo = "a/b" })
		t = nav.reduce(t, { type = "SEARCH_DONE", results = {}, query = "x" })
		assert(t.data == nil, "search result dropped outside picker")
	end)
end)
