local testing = require("ascii-ui.testing")
local App = require("ascii-ui-actions.ui.app")

describe("App component", function()
	it("renders the default title", function()
		local screen = testing.render(App)
		assert(screen:hasText("ascii-ui-actions"), "title should be rendered")
	end)

	it("increments the counter when +1 is pressed", function()
		local screen = testing.render(App)
		assert(screen:hasText("count: 0"), "counter starts at 0")
		screen:select("+1")
		assert(screen:hasText("count: 1"), "counter increments on select")
	end)

	it("resets the counter", function()
		local screen = testing.render(App)
		screen:select("+1")
		screen:select("+1")
		screen:select("reset")
		assert(screen:hasText("count: 0"), "counter resets to 0")
	end)
end)
