local Demo = require("ascii-ui-actions.ui.demo")
local testing = require("ascii-ui.testing")
local eq = require("tests.assertions").eq

describe("Demo", function()
	it("renders title, breadcrumb, rows, status and hint", function()
		local lines = testing.render(Demo):toLines()
		eq(" ascii-ui-actions", lines[1])
		eq(" foo/bar › ci.yml", lines[2])
		assert(lines[3]:find("build", 1, true), "run row: " .. lines[3])
		assert(lines[3]:find("2m14s", 1, true), "duration: " .. lines[3])
		assert(lines[#lines - 1]:find("fetched", 1, true), "status: " .. lines[#lines - 1])
		assert(lines[#lines]:find("? keys", 1, true), "hint: " .. lines[#lines])
	end)

	it("keeps the branch column aligned across rows", function()
		local lines = testing.render(Demo):toLines()
		local starts = vim.iter({ lines[3], lines[4], lines[5] })
			:map(function(l)
				return l:find("main", 1, true) or l:find("feature", 1, true)
			end)
			:totable()
		eq({ starts[1], starts[1], starts[1] }, starts)
	end)

	it("toggles the keymap overlay in place with ? keys", function()
		local screen = testing.render(Demo)
		local initial = table.concat(screen:toLines(), "\n")
		screen:select("? keys")
		assert(screen:hasText("rerun"), "overlay explains rerun")
		assert(screen:hasText("cancel"), "overlay explains cancel")
		assert(not screen:hasText("docker"), "run list hidden while overlay open")
		screen:select("? close")
		eq(initial, table.concat(screen:toLines(), "\n"))
	end)

	it("surfaces errors in the status region, never silently", function()
		local ErrorDemo = require("ascii-ui").createComponent("ErrorDemo", function()
			return Demo({ show_error = true })
		end)
		local screen = testing.render(ErrorDemo)
		assert(screen:hasText("gh not found"), "error message visible")
		assert(screen:hasText("gh auth login"), "hint visible")
	end)
end)
